На тесты гитхаба до ПР
DavidovichIvan/java-shareit pull request #1
Opened 2023-07-25 10:33 UTC by DavidovichIvan

2023-07-25 10:50 UTC, DavidovichIvan commented
Привет, я так понял этот блок только заготовка для след. спринтов. Тесты постмана победил. Спасибо за ревью.

2023-07-25 17:13 UTC, EugeneLenkevich commented
> Привет, я так понял этот блок только заготовка для след. спринтов. Тесты постмана победил. Спасибо за ревью.

Ну да, будем допиливать потихоньку :)

2023-07-25 17:16 UTC, EugeneLenkevich requested changes
Привет, Иван, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-07-25 17:16 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/exceptions/DataBaseNotFoundException.java
> +        this.message = "Пользователь/вещь не найдены.";
Сюда б кстати еще добавить ид или другие данные по которым вещь ищется, иначе трудновато будет потом по логу разбираться, если, конечно, наши любимые тесты постмана не сломает)

2023-07-25 17:16 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        userStorage.getUser(item.getOwnerId())
Вот тут мы лезем во внутренности репозитория, а что если метод создать и вызывать уже его тут, так мы спрячем детали внутренней реализации :)

2023-07-25 17:16 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (!userStorage.getUser(item.getOwnerId())
Аналогично, внутреннюю структуру лучше спрятать за методом соответствующего хранилища :)

2023-07-25 17:16 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (text.isBlank()) {
Если text == null то мы получим тут ошибку, тут бы проверку на null :)

2023-07-25 17:16 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static ItemDto itemToDto(Item item) {             //наверное метод static по смыслу
Объект, который производит маппинг можно, так же, сделать отдельным бином. Это позволит оформить все в единой(спринговой) парадигме и лишний раз избежать использования статических методов, которые являются жесткими ссылками.

То есть добавляем аннтоацию @Component или @Service, убираем static и инжектим в сервисы/контроллеры как и другие зависимости

Однако, это вопрос дискуссионный.
С другой стороны, в этом случае, мы пихаем в спринговый контекст дополнительный бин :)

Что думаешь на этот счет? :)

2023-07-25 17:16 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Запрос на добавление вещи");
Это все логирование опустить бы на уровень сервиса,так как оно больше относится к бизнес-логике. На уровне контроллеров мы все таки оперирируем (маршрутизируем) http-запросами  :)

2023-07-26 07:36 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/exceptions/DataBaseNotFoundException.java
> +        this.message = "Пользователь/вещь не найдены.";
В принципе плюс минус так и сделано. Для этого второй конструктор в который сообщение передается. Добавил в классах InMemory, чтобы передавались айдишники в исключения.

2023-07-26 07:41 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        userStorage.getUser(item.getOwnerId())
Если понял правильно, завернул эту часть в private-метод  addItemToUser(item)

2023-07-26 07:50 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (!userStorage.getUser(item.getOwnerId())
Также сделал. Ну я понял то есть что другой бин ковыряется сам внутри себя, а мы только инициируем процесс.

2023-07-26 07:52 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (text.isBlank()) {
допилил -  if (text == null || text.isBlank())

2023-07-26 07:57 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static ItemDto itemToDto(Item item) {             //наверное метод static по смыслу
Подход понятен, логично в принципе. Могу предположить, что если функционал маппинга небольшой, как у меня сейчас, то можно абстрактными методами ограничиться. Если маппер разрастется, то наверное лучше отдельным бином запилить. В этом ТЗ вообщем-то конкретики не было никакой по маперам, я поэтому сделал как заготовку. Пока оставлю тогда как есть, посмотрю как в след.ТЗ будут события развиваться.

2023-07-26 08:05 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Запрос на добавление вещи");
Переделал для ItemController и UserController.

2023-07-26 08:12 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static ItemDto itemToDto(Item item) {             //наверное метод static по смыслу
В целом без особой разницы на самом деле, вообще, это вопрос скорее единообразия

2023-07-26 08:12 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (!userStorage.getUser(item.getOwnerId())
Ага, именно

2023-07-26 10:36 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-08-12 16:51 UTC, merged