Add bookings
DavidovichIvan/java-shareit pull request #2
Opened 2023-08-12 16:50 UTC by DavidovichIvan

2023-08-12 18:01 UTC, DavidovichIvan commented
Доброго времени суток.
Чуть пупок не надорвал, очень объемное ТЗ) Тесты все прошел, хотя без нецензурных выражений не обошлось.

Не уверен, что между уровнями правильно все раскидал. 
Репозитории все без реализации, так как она как будто бы не требуется, все методы либо сами работают либо через @Query.
Ввел классы-валидаторы, которые по смыслу что-то среднее между мапперами и хранилищами.

Спасибо за ревью.

2023-08-13 05:25 UTC, EugeneLenkevich requested changes
Привет, Иван, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

В первую очередь, посмотри методы Optional еще раз, с помощью них можно некоторые вещи записать попроще, но это все синтаксический сахар.

Далее, лучше лишний раз не писать нативный SQL, вся суть JPA в том чтобы сократить трудозатраты на написание sql-кода, а когда мы его пишем руками получается что мы не используем интрумент на полную мощность и только переусложняем код :)
Нативный SQL конечно же пишут, но в тех случаях когда без него уже точн не обойтись - какие то сложные аналитиеские запросы, например, но обычные операции вставки и обновления сущностей лучше стандартными средствами JPA делать :)

2023-08-13 05:25 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query(value = "update booking b set status = ?1 where booking_id = ?2", nativeQuery = true)
Тут можно было ина HQL сделать запрос, было бы чутка покорочек, но не суть.

?1, ?2 - лучше конечно плейхолдеры, ка кто надежней и проще читать потом :)

update booking b set status = :status where booking_id = :bookingId

А, в целом, можно было просто достать сущность, поменять статус и сохранить через методы репозитория. Тут может потечь наша ORM-абстракция, так как, в общем случае, на уровне JPA могут быть навешаны различные обработчики, например, те что устанавливают дату модификации, именившего пользователя и пр

Получается что мы тут смешиваем разные парадигмы - реляционную и то что нам дает JRM. В реальной жизни, правда, такое бывает постоянно, обычным апдейтом гораздо эффективнее обновить сущность, но надо иметь в виду что абстракция может протечь, мы потеряем гибкость инструмента и, наоборот, создадим себе проблемы.  В общем так делать можно в целях оптимизации, но в тех случаях когда по другому уже не получается :)

https://ru.wikibrief.org/wiki/Leaky_abstraction

2023-08-13 05:25 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +    public List<Booking> bookingsSearchValidate(int bookerId, String bookingsState) {
String bookingsState

А что если вместо этого испльзовать enum :)

2023-08-13 05:25 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +            case ("ALL"):
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2023-08-13 05:25 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +        Optional<Booking> booking = bookingRepository.getLastBooking(i.getOwnerId(), i.getId(), LocalDateTime.now());
Тут можно чутка попроще написать, примерно так :)

bookingRepository.getLastBooking(...).ifPresent(foundBooking->{
// перекладываем в dto
});

2023-08-13 05:25 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/exceptions/DataBaseNotFoundException.java
>  public class DataBaseNotFoundException extends RuntimeException {
DataBaseNotFoundException - дословно "база данных не найдена", может лучше назвать просто NotFoundException :)

А уже же есть соответствие исключений кодам http на уровне контроллеров, через сооветвествующий @ControllerAdvice, можно ли тут это вовсе убрать, по идее это обязанность уровня контроллеров ставить соответствие исключений кодам http? :)

2023-08-13 05:25 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        log.info("Запрос на добавление комментария");
Еще б в лог еще добавить itemId и userId, так гораздо проще будет разбираться что в логе происходит :)

2023-08-13 05:25 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +        Optional<Item> item = itemRepository.findById(itemId);
Тут можно попроще поступить :)

 boolean exists = itemRepository.existsById(itemId);


https://stackoverflow.com/questions/7471625/fastest-check-if-row-exists-in-postgresql

2023-08-13 05:25 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +        Optional<Booking> book = bookingRepository.getByIdAndBookerId(itemId, authorId);
Тут тоже попроще можно записать :)

Booking book = bookingRepository.getByIdAndBookerId(itemId, authorId).orElseThrow( -> new DataBaseException(...));

![image](https://github.com/DavidovichIvan/java-shareit/assets/109306643/4367168e-a914-451f-8b7b-289801be3a1d)


https://habr.com/ru/articles/346782/

2023-08-13 05:36 UTC, EugeneLenkevich commented
> Доброго времени суток. Чуть пупок не надорвал, очень объемное ТЗ) Тесты все прошел, хотя без нецензурных выражений не обошлось.
> 
> Не уверен, что между уровнями правильно все раскидал. Репозитории все без реализации, так как она как будто бы не требуется, все методы либо сами работают либо через @query. Ввел классы-валидаторы, которые по смыслу что-то среднее между мапперами и хранилищами.

Ну, мы, по сути, переписали полностью слой хранилища данных :D

По слоям в данном случае главное чтобы логики в контроллерах не было :)

На счет репозиториев. Таки да, тут очень много магии, начиная с той, что генерирует SQL-запросы, а, далее, есть другая магия, которая по описанию методов (и схемы данных) в интерфейсе-репозитории генерирует код в рантайме. Но тут на самом деле лучше не мудрить и писать код самым простым и очевидныи образом как минимум на первых порах не думая про производительность. 

А еще. Есть вот такие две настройки

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

если они включены, то мы, например прогоняя тесты, можем видеть какой sql генерируется и вообще понимать что у нас в итоге происходит

2023-08-13 12:08 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query(value = "update booking b set status = ?1 where booking_id = ?2", nativeQuery = true)
1) Переделал большую часть query, несколько оставил нативные. Идея ясна, по максимуму работать не с БД, а со связанными сущностями. В теории к сожалению почти не касались вопроса написания на JPQL, поэтому на простейших запросах понятно, но в целом синтаксис не очевиден пока что.

2) По методам Optional пробежался, переделал. Как я понял в итоге если без явного создания Optional объекта можно обойтись сразу логическим действием, то лучше так делать.

3) По переменным в запросах переделал с ?1, ?2 на :ownerId и т.д.  В части запросов, в части оставил для наглядности для себя.

4) по методу update - cпасибо за инфу. Я когда делал, рассуждал, что наоборот вроде как если мне только 1 поле поменять то зачем я буду сущность дергать туда-сюда. Переделал.  Старый метод в репозитории оставил для себя, закомментил.

2023-08-13 12:09 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +    public List<Booking> bookingsSearchValidate(int bookerId, String bookingsState) {
Переделал. Думал об этом в процессе)

2023-08-13 12:10 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +            case ("ALL"):
Идея как я понял в том, чтобы делать программу модульной там, где можно самостоятельный функционал отделить, то есть инкапсуляция по cути. Если не критично то в этой части я правки вносить не стал, новая для меня инфа, поизучаю отдельно.

2023-08-13 12:10 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +        Optional<Booking> booking = bookingRepository.getLastBooking(i.getOwnerId(), i.getId(), LocalDateTime.now());
Переделал. Как я понял в итоге если без Optional объекта можно обойтись сразу логическим действием, то лучше так делать.

2023-08-13 12:11 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/exceptions/DataBaseNotFoundException.java
>  public class DataBaseNotFoundException extends RuntimeException {
Согласен, изменил название исключения и поубирал избыточные аннотации из исключений.

2023-08-13 12:12 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        log.info("Запрос на добавление комментария");
Прошелся по выводу логов, там где по смыслу не хватало отсылочных данных - добавил.

2023-08-13 12:12 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +        Optional<Item> item = itemRepository.findById(itemId);
Не знал про такой метод, переделал в этом месте, постараюсь запомнить, выглядит как востребованный.

2023-08-13 12:13 UTC, DavidovichIvan commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +        Optional<Booking> book = bookingRepository.getByIdAndBookerId(itemId, authorId);
Прошелся по валидаторам, откорректировал. Удобнее безусловно. Вспомнил, что ты уже подсказывал эту тему. Голова дырявая) Последние спринты я себя потерявшимся ребенком ощущаю в потоке информации и задаюсь вопросом как спецы это все знают)

2023-08-13 12:17 UTC, DavidovichIvan commented
Спасибо, все понятно.

2023-08-13 15:36 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +            case ("ALL"):
Да не, не критично, но этот паттерн очень любят спрашивать на собеседованиях, потому лучше его знать как минимум теоретически, идея то сама по себе простая

2023-08-13 15:38 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +        Optional<Booking> book = bookingRepository.getByIdAndBookerId(itemId, authorId);
Как есть слона, ответ - по маленьким кусочкам, не все сразу, это нормально, это всегда и везде так при изучении чего то нового)

2023-08-13 15:52 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query(value = "update booking b set status = ?1 where booking_id = ?2", nativeQuery = true)
> 1. Переделал большую часть query, несколько оставил нативные. Идея ясна, по максимуму работать не с БД, а со связанными сущностями. В теории к сожалению почти не касались вопроса написания на JPQL, поэтому на простейших запросах понятно, но в целом синтаксис не очевиден пока что.

Ну на самом деле HQL очень простой, в том смысле что он базируется на SQL, только по другому джоины записываются и в общем то и все 

> 2. По методам Optional пробежался, переделал. Как я понял в итоге если без явного создания Optional объекта можно обойтись сразу логическим действием, то лучше так делать.

Суть Optional в том, чтобы вернуть из метода значение которое может быть null скажем так более безопасным способом. Плюс мы можем писать код таким образом в функциональном стиле. 
И вот такой пример приведу, допустим у нас есть бъект со вложенными объектами, которые могут быть null и нам надо достать оттуда значение

`var code = record.getAddress().getCity().getCode();`

Если мы будем писать в обычном императином стиле у нас будет куча if(value==null), то есть ветвлений и пр

В функциональном стиле у нас будет прямая структура

```
Optional.ofNullable(record)
.map(Record::getAddress)
.map(Address::getCity)
.map(City::getCode)
.orElse(null);
```

Но, опять таки, optional - это куча мелких объектов, лишняя нагрузка на GC


> 3. По переменным в запросах переделал с ?1, ?2 на :ownerId и т.д.  В части запросов, в части оставил для наглядности для себя.

Ок

> 4. по методу update - cпасибо за инфу. Я когда делал, рассуждал, что наоборот вроде как если мне только 1 поле поменять то зачем я буду сущность дергать туда-сюда. Переделал.  Старый метод в репозитории оставил для себя, закомментил.

Вот меня всегда это тоже смущает, ради изменения одного маленького поля мы должны пересохранять целую 
огромную огромную сущность
Однако, цель ORM - это экономия рабочего времени команды, разработка с ним гораздо быстрее. Да и багов с ним гораздо меньше, а поддерживать SQL-запросы, особенно когда они достаточно сложные - это тоде отдельное развлечение. Чаще всего основную часть логики пишут на ORM потому что это быстро и в общем то достаточно быстро работает, а вот там где тормозит там можно воткнуть голый SQL, но, все равно, чаще проще индексы навесить на таблички, оптимизировать HQL-запросы и пр. Но это отдельная и непростая история)

2023-08-13 15:55 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-08-16 15:10 UTC, merged